### ISSUE TITLE
Spanish support please

### ISSUE THREAD

**Issue by MiClobiMC** [pgeorgis/Automatic_Transcription#1]
It is possible to add for the Spanish language

**Comment by pgeorgis** [comment]
I've added preliminary support for Spanish. The default transcription scheme is for standard Peninsular Spanish, but there are options for transcribing other dialects. For example, set "distincion = False" to render Latin American Spanish without /θ/, "ceceo = True" to transcribe the pronunciation of regions such as southern Andalusia, or "yeismo = False" to distinguish <y> /ʝ/ and <ll> /ʎ/.
